# Generated by Django 5.1.4 on 2026-08-04 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ayudas', '0001_initial'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coincidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=70, help_text='100 si coinciden ciudad y zona; 70 si solo coincide la ciudad.', verbose_name='Nivel de coincidencia')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Detectada el')),
                ('ayuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coincidencias', to='ayudas.ofertaayuda', verbose_name='Oferta de ayuda')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coincidencias', to='solicitudes.solicitudayuda', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Coincidencia',
                'verbose_name_plural': 'Coincidencias',
                'ordering': ['-score', '-creado'],
                'indexes': [models.Index(fields=['score', 'creado'], name='coincidenci_score_9817de_idx')],
                'constraints': [models.UniqueConstraint(fields=('solicitud', 'ayuda'), name='coincidencia_unica_solicitud_ayuda')],
            },
        ),
    ]
