# Generated by Django 5.1.4 on 2026-08-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('RESUELTA', 'Resuelta'), ('BLOQUEADA', 'Bloqueada')], db_index=True, default='ACTIVA', max_length=12, verbose_name='Estado')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de publicacion')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('ip_origen', models.GenericIPAddressField(blank=True, help_text='Se registra para poder rastrear abuso. No se muestra al publico.', null=True, verbose_name='IP de origen')),
                ('nota_admin', models.TextField(blank=True, help_text='Visible solo en el panel. Por ejemplo: por que se cerro o bloqueo.', verbose_name='Nota interna del administrador')),
                ('ciudad', models.CharField(db_index=True, max_length=100, verbose_name='Ciudad')),
                ('zona', models.CharField(help_text='Barrio, vereda, comuna o punto de referencia.', max_length=150, verbose_name='Zona o barrio')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('contacto_telefono', models.CharField(blank=True, max_length=30, verbose_name='Telefono o WhatsApp')),
                ('contacto_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electronico')),
                ('alias', models.CharField(help_text='Puedes usar un apodo, o el nombre de tu organizacion.', max_length=100, verbose_name='Nombre o alias')),
                ('tipo_ayuda', models.CharField(choices=[('ALIMENTOS', 'Alimentos'), ('AGUA', 'Agua'), ('ALOJAMIENTO', 'Alojamiento'), ('ROPA', 'Ropa'), ('TRANSPORTE', 'Transporte'), ('MEDICAMENTOS', 'Medicamentos e insumos basicos'), ('ELECTRICIDAD', 'Carga de celular / electricidad'), ('MASCOTAS', 'Ayuda para mascotas'), ('DONACIONES', 'Donaciones'), ('MANO_DE_OBRA', 'Mano de obra'), ('OTRO', 'Otro')], db_index=True, max_length=20, verbose_name='Tipo de ayuda disponible')),
                ('cantidad', models.CharField(help_text='Ej: 5 mercados, 2 habitaciones, 20 litros de agua, 1 camioneta.', max_length=150, verbose_name='Cantidad disponible')),
                ('descripcion', models.TextField(help_text='Detalla que ofreces y cualquier condicion (horarios, si entregas a domicilio, etc).', verbose_name='Descripcion')),
                ('disponibilidad', models.CharField(choices=[('INMEDIATA', 'Inmediata'), ('HOY', 'Hoy'), ('PROXIMOS_DIAS', 'Proximos dias')], db_index=True, default='INMEDIATA', max_length=15, verbose_name='Disponibilidad')),
            ],
            options={
                'verbose_name': 'Oferta de ayuda',
                'verbose_name_plural': 'Ofertas de ayuda',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['estado', 'disponibilidad'], name='ayudas_ofer_estado_a4af57_idx'), models.Index(fields=['ciudad', 'tipo_ayuda'], name='ayudas_ofer_ciudad_2f73ad_idx'), models.Index(fields=['latitud', 'longitud'], name='ayudas_ofer_latitud_661406_idx')],
            },
        ),
    ]
