# Generated by Django 5.1.4 on 2026-08-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaayuda',
            name='foto',
            field=models.ImageField(blank=True, help_text='Una foto de lo que ofreces ayuda a que las personas confien.', null=True, upload_to='ayudas/%Y/%m/', verbose_name='Foto (opcional)'),
        ),
    ]
