# Generated by Django 5.1.4 on 2026-08-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudas', '0003_ofertaayuda_busqueda_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaayuda',
            name='departamento',
            field=models.CharField(blank=True, db_index=True, help_text='Ej: Caldas, Risaralda, Valle del Cauca. Ayuda a ubicar el municipio.', max_length=60, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='ofertaayuda',
            name='ciudad',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Ciudad o municipio'),
        ),
    ]
