# Generated by Django 5.1.4 on 2026-08-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('descripcion', models.TextField(help_text='Resumen breve de que contiene el enlace. No copies el comunicado completo.', verbose_name='Descripcion')),
                ('institucion', models.CharField(db_index=True, help_text='Nombre exacto de la entidad que publico la informacion. Ej: Servicio Geologico Colombiano, UNGRD, Alcaldia de Armenia.', max_length=150, verbose_name='Institucion')),
                ('url', models.URLField(help_text='Enlace directo a la pagina oficial. Es obligatorio: sin fuente verificable la entrada no debe publicarse.', max_length=500, verbose_name='URL de la fuente oficial')),
                ('categoria', models.CharField(choices=[('SISMICA', 'Informacion sismica'), ('RECOMENDACIONES', 'Recomendaciones'), ('COMUNICADOS', 'Comunicados'), ('CENTROS', 'Centros de atencion'), ('MUNICIPAL', 'Informacion municipal'), ('DEPARTAMENTAL', 'Informacion departamental')], db_index=True, max_length=20, verbose_name='Categoria')),
                ('fecha', models.DateField(db_index=True, help_text='Fecha en que la institucion publico esta informacion.', verbose_name='Fecha de la informacion')),
                ('destacada', models.BooleanField(default=False, help_text='Las entradas destacadas aparecen primero en el listado.', verbose_name='Destacar')),
                ('publicada', models.BooleanField(default=True, help_text='Desmarcalo para ocultarla del sitio sin borrarla.', verbose_name='Publicada')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Agregada el')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
            ],
            options={
                'verbose_name': 'Informacion oficial',
                'verbose_name_plural': 'Informacion oficial',
                'ordering': ['-destacada', '-fecha', '-creado'],
                'indexes': [models.Index(fields=['categoria', 'fecha'], name='informacion_categor_9f78d7_idx')],
            },
        ),
    ]
