# Generated by Django 5.1.4 on 2026-08-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteComunitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('RESUELTA', 'Resuelta'), ('BLOQUEADA', 'Bloqueada')], db_index=True, default='ACTIVA', max_length=12, verbose_name='Estado')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de publicacion')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('ip_origen', models.GenericIPAddressField(blank=True, help_text='Se registra para poder rastrear abuso. No se muestra al publico.', null=True, verbose_name='IP de origen')),
                ('nota_admin', models.TextField(blank=True, help_text='Visible solo en el panel. Por ejemplo: por que se cerro o bloqueo.', verbose_name='Nota interna del administrador')),
                ('ciudad', models.CharField(db_index=True, max_length=100, verbose_name='Ciudad')),
                ('zona', models.CharField(help_text='Barrio, vereda, comuna o punto de referencia.', max_length=150, verbose_name='Zona o barrio')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('tipo_reporte', models.CharField(choices=[('DANOS', 'Danos visibles en estructuras'), ('VIA_BLOQUEADA', 'Via bloqueada'), ('FALTA_AGUA', 'Falta de agua'), ('FALTA_ALIMENTOS', 'Falta de alimentos'), ('ALOJAMIENTO', 'Personas que necesitan alojamiento'), ('SERVICIOS', 'Sin luz, gas o comunicaciones'), ('OTRA', 'Otra situacion')], db_index=True, max_length=20, verbose_name='Tipo de reporte')),
                ('urgencia', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], db_index=True, default='MEDIA', max_length=10, verbose_name='Nivel de urgencia')),
                ('descripcion', models.TextField(help_text='Describe que viste, donde y cuando. Se lo mas concreto posible.', verbose_name='Descripcion de la situacion')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='reportes/%Y/%m/', verbose_name='Foto (opcional)')),
                ('reportado_por', models.CharField(blank=True, help_text='Opcional. Puedes reportar de forma anonima.', max_length=100, verbose_name='Nombre o alias de quien reporta')),
            ],
            options={
                'verbose_name': 'Reporte comunitario',
                'verbose_name_plural': 'Reportes comunitarios',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['estado', 'urgencia'], name='reportes_re_estado_f8412a_idx'), models.Index(fields=['ciudad', 'tipo_reporte'], name='reportes_re_ciudad_f1b13c_idx'), models.Index(fields=['latitud', 'longitud'], name='reportes_re_latitud_bf8e2d_idx')],
            },
        ),
    ]
