# Generated by Django 5.1.4 on 2026-08-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportecomunitario',
            name='busqueda_lugar',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=260),
        ),
    ]
