# Generated by Django 5.1.4 on 2026-08-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('RESUELTA', 'Resuelta'), ('BLOQUEADA', 'Bloqueada')], db_index=True, default='ACTIVA', max_length=12, verbose_name='Estado')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de publicacion')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('ip_origen', models.GenericIPAddressField(blank=True, help_text='Se registra para poder rastrear abuso. No se muestra al publico.', null=True, verbose_name='IP de origen')),
                ('nota_admin', models.TextField(blank=True, help_text='Visible solo en el panel. Por ejemplo: por que se cerro o bloqueo.', verbose_name='Nota interna del administrador')),
                ('ciudad', models.CharField(db_index=True, max_length=100, verbose_name='Ciudad')),
                ('zona', models.CharField(help_text='Barrio, vereda, comuna o punto de referencia.', max_length=150, verbose_name='Zona o barrio')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('contacto_telefono', models.CharField(blank=True, max_length=30, verbose_name='Telefono o WhatsApp')),
                ('contacto_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electronico')),
                ('alias', models.CharField(help_text='Puedes usar un apodo si prefieres no dar tu nombre real.', max_length=100, verbose_name='Nombre o alias')),
                ('personas_afectadas', models.PositiveIntegerField(default=1, help_text='Cuantas personas necesitan esta ayuda, contandote a ti.', verbose_name='Numero de personas afectadas')),
                ('tipo_ayuda', models.CharField(choices=[('ALIMENTOS', 'Alimentos'), ('AGUA', 'Agua'), ('ALOJAMIENTO', 'Alojamiento'), ('ROPA', 'Ropa'), ('TRANSPORTE', 'Transporte'), ('MEDICAMENTOS', 'Medicamentos e insumos basicos'), ('ELECTRICIDAD', 'Carga de celular / electricidad'), ('MASCOTAS', 'Ayuda para mascotas'), ('OTRO', 'Otro')], db_index=True, max_length=20, verbose_name='Tipo de ayuda necesaria')),
                ('urgencia', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], db_index=True, default='MEDIA', max_length=10, verbose_name='Nivel de urgencia')),
                ('descripcion', models.TextField(help_text='Explica con detalle que necesitas. Entre mas claro, mas facil sera ayudarte.', verbose_name='Descripcion')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='solicitudes/%Y/%m/', verbose_name='Foto (opcional)')),
            ],
            options={
                'verbose_name': 'Solicitud de ayuda',
                'verbose_name_plural': 'Solicitudes de ayuda',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['estado', 'urgencia'], name='solicitudes_estado_2c901d_idx'), models.Index(fields=['ciudad', 'tipo_ayuda'], name='solicitudes_ciudad_365e81_idx'), models.Index(fields=['latitud', 'longitud'], name='solicitudes_latitud_eb03e3_idx')],
            },
        ),
    ]
