# Generated by Django 5.1.4 on 2026-08-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('RESUELTA', 'Resuelta'), ('BLOQUEADA', 'Bloqueada')], db_index=True, default='ACTIVA', max_length=12, verbose_name='Estado')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de publicacion')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('ip_origen', models.GenericIPAddressField(blank=True, help_text='Se registra para poder rastrear abuso. No se muestra al publico.', null=True, verbose_name='IP de origen')),
                ('nota_admin', models.TextField(blank=True, help_text='Visible solo en el panel. Por ejemplo: por que se cerro o bloqueo.', verbose_name='Nota interna del administrador')),
                ('ciudad', models.CharField(db_index=True, max_length=100, verbose_name='Ciudad')),
                ('zona', models.CharField(help_text='Barrio, vereda, comuna o punto de referencia.', max_length=150, verbose_name='Zona o barrio')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('nombre', models.CharField(help_text='Ej: Salon comunal La Milagrosa, Parroquia San Jose.', max_length=150, verbose_name='Nombre del lugar')),
                ('tipo', models.CharField(choices=[('ACOPIO', 'Centro de acopio'), ('ALIMENTOS', 'Entrega de alimentos'), ('AGUA', 'Punto de agua'), ('REFUGIO', 'Refugio o albergue'), ('DONACIONES', 'Recepcion de donaciones'), ('CARGA', 'Punto de carga de celulares'), ('SALUD', 'Atencion en salud comunitaria'), ('ORGANIZACION', 'Organizacion comunitaria'), ('OTRO', 'Otro')], db_index=True, max_length=15, verbose_name='Tipo de punto')),
                ('horario', models.CharField(help_text="Ej: Lunes a sabado de 8am a 6pm. O 'Las 24 horas'.", max_length=150, verbose_name='Horario de atencion')),
                ('descripcion', models.TextField(help_text='Que se hace en este punto, que se entrega o que se recibe.', verbose_name='Descripcion')),
                ('contacto', models.CharField(blank=True, help_text='Telefono, correo o nombre de la persona encargada.', max_length=200, verbose_name='Contacto')),
                ('direccion', models.CharField(blank=True, help_text='Direccion exacta si la conoces.', max_length=250, verbose_name='Direccion')),
                ('fuente_informacion', models.CharField(help_text="De donde salio este dato. Ej: 'Lo vi personalmente', 'Me lo dijo un vecino'.", max_length=200, verbose_name='Fuente de la informacion')),
                ('disponibilidad', models.CharField(choices=[('ACTIVO', 'Activo'), ('NO_DISPONIBLE', 'No disponible temporalmente'), ('CERRADO', 'Cerrado')], db_index=True, default='ACTIVO', max_length=15, verbose_name='Estado del punto')),
                ('verificado', models.BooleanField(default=False, help_text='Marcalo SOLO si confirmaste que este punto existe y opera. Mientras este sin marcar, el sitio avisa que es informacion aportada por la comunidad y sin verificar.', verbose_name='Verificado por la administracion')),
            ],
            options={
                'verbose_name': 'Punto de ayuda',
                'verbose_name_plural': 'Puntos de ayuda',
                'ordering': ['-verificado', '-creado'],
                'indexes': [models.Index(fields=['estado', 'disponibilidad'], name='puntos_punt_estado_63703a_idx'), models.Index(fields=['ciudad', 'tipo'], name='puntos_punt_ciudad_bf4a11_idx'), models.Index(fields=['latitud', 'longitud'], name='puntos_punt_latitud_37319b_idx')],
            },
        ),
    ]
