# Generated by Django 5.1.4 on 2026-08-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoayuda',
            name='foto',
            field=models.ImageField(blank=True, help_text='Una foto ayuda a que las personas reconozcan el lugar al llegar.', null=True, upload_to='puntos/%Y/%m/', verbose_name='Foto del lugar (opcional)'),
        ),
    ]
