# Generated by Django 5.1.4 on 2026-08-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0003_puntoayuda_busqueda_lugar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puntoayuda',
            options={'ordering': ['-prioritario', '-destacado', '-verificado', '-creado'], 'verbose_name': 'Punto de ayuda', 'verbose_name_plural': 'Puntos de ayuda'},
        ),
        migrations.AddField(
            model_name='puntoayuda',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Aparece primero en los listados.', verbose_name='⭐ Punto recomendado'),
        ),
        migrations.AddField(
            model_name='puntoayuda',
            name='elementos_no_recibidos',
            field=models.TextField(blank=True, help_text='Un elemento por linea. Evita que la gente lleve cosas que van a ser rechazadas. Ej: Medicamentos / Alimentos perecederos.', verbose_name='Que NO reciben'),
        ),
        migrations.AddField(
            model_name='puntoayuda',
            name='elementos_recibidos',
            field=models.TextField(blank=True, help_text='Un elemento por linea. Ej: Cobijas / Toallas / Kits de aseo.', verbose_name='Que reciben'),
        ),
        migrations.AddField(
            model_name='puntoayuda',
            name='fecha_verificacion',
            field=models.DateField(blank=True, help_text='Cuando se comprobo por ultima vez que esta informacion sigue vigente.', null=True, verbose_name='Fecha de verificacion'),
        ),
        migrations.AddField(
            model_name='puntoayuda',
            name='hora_verificacion',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de verificacion'),
        ),
        migrations.AddField(
            model_name='puntoayuda',
            name='prioritario',
            field=models.BooleanField(default=False, help_text='Se resalta como punto critico durante la emergencia.', verbose_name='🚨 Atencion prioritaria'),
        ),
        migrations.AddField(
            model_name='puntoayuda',
            name='servicios',
            field=models.TextField(blank=True, help_text='Un servicio por linea. Ej: Alojamiento / Alimentacion / Atencion a menores.', verbose_name='Que se puede hacer alli'),
        ),
        migrations.AddField(
            model_name='puntoayuda',
            name='url_fuente',
            field=models.URLField(blank=True, help_text='Enlace a la publicacion oficial que respalda esta informacion.', max_length=500, verbose_name='Enlace a la fuente'),
        ),
        migrations.AddField(
            model_name='puntoayuda',
            name='verificacion',
            field=models.CharField(choices=[('CONFIRMADO', 'Confirmado por fuente oficial'), ('POR_CONFIRMAR', 'Pendiente de confirmacion oficial'), ('CERRADO', 'Cerrado o inactivo')], db_index=True, default='POR_CONFIRMAR', help_text='CONFIRMADO solo si la informacion proviene de una fuente oficial o de una organizacion reconocida.', max_length=15, verbose_name='Estado de la informacion'),
        ),
        migrations.AlterField(
            model_name='puntoayuda',
            name='tipo',
            field=models.CharField(choices=[('ACOPIO', 'Centro de acopio'), ('ALIMENTOS', 'Entrega de alimentos'), ('AGUA', 'Punto de agua'), ('REFUGIO', 'Albergue temporal'), ('DONACIONES', 'Recepcion de donaciones'), ('CARGA', 'Punto de carga de celulares'), ('SALUD', 'Atencion medica'), ('ORGANIZACION', 'Organizacion comunitaria'), ('SANGRE', 'Donacion de sangre'), ('ALOJAMIENTO', 'Alojamiento temporal'), ('ROPA', 'Recepcion de ropa'), ('ABRIGO', 'Recepcion de cobijas y colchonetas'), ('ASEO', 'Recepcion de kits de aseo'), ('BEBES', 'Articulos para bebes'), ('ANIMALES', 'Ayuda para animales'), ('DINERO', 'Canal oficial de donacion economica'), ('SOCORRO', 'Organismo de socorro'), ('INFORMACION', 'Punto de informacion'), ('BUSQUEDA', 'Personas desaparecidas o busqueda'), ('OTRO', 'Otro')], db_index=True, max_length=20, verbose_name='Tipo de punto'),
        ),
        migrations.AddIndex(
            model_name='puntoayuda',
            index=models.Index(fields=['verificacion', 'ciudad'], name='puntos_punt_verific_d060f9_idx'),
        ),
    ]
